apiVersion: v1
kind: Pod
metadata:
  name: csgo-pod
spec:
  containers:
  - name: csgo-container
    image: boomland/csgo_fastapi:v1
    env:
      - name: PORT
        value: "8080"
      - name: IP
        value: "0.0.0.0"
    ports:
      - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 60
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 60
      periodSeconds: 10
  restartPolicy: OnFailure