apiVersion: v1
kind: Pod
metadata:
  name: sleepy-limited-pod
spec:
  containers:
  - name: sleepy-limited-container
    image: alpine
    command: ["sleep"]
    args: ["60"]
    resources:
      requests:
        memory: "32Mi"
        cpu: "1"
      limits:
        memory: "64Mi"
        cpu: "2"
  restartPolicy: OnFailure
